<?php

namespace Esimed\CarLocation\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ForfaitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForfaitRepository extends EntityRepository {
}